---

application_name: "{{ djl_modelmanager_name }}"

service_image: "quay.io/redhat_naps_da/{{ application_name }}"
service_image_tag: 0.0.1

application_configmap: "{{ application_name }}"

helm_tar_url: "/u01/labs/mw/redhat-na-ssa/djl-intro/{{ application_name }}/target/helm/openshift/{{ application_name }}"
# helm_tar_url: "https://github.com/redhat-na-ssa/djl-intro/raw/main/{{ application_name }}/helm/{{ application_name }}-{{ service_image_tag }}.tar.gz"

model_pv_capacity: 5Gi
