---

- name: "deploy amq streams operator in {{ namespace_amq_streams_operator }}"
  import_role:
    name: ../roles/operator_olm
  vars:
    operator_name: amq-streams-operator
    packagemanifest: "{{ amq_streams_operator_packagemanifest }}"
    subscription_channel: "{{ amq_streams_operator_subscription_channel }}"
    subscription_namespace: "{{ namespace_amq_streams_operator }}"
    subscription_name: "{{ amq_streams_operator_subscription_name }}"
    automatic_installplan_approval: "{{ amq_streams_operator_subscription_automatic_installplan_approval }}"
    subscription_starting_csv: "{{ amq_streams_subscription_starting_csv }}"
    csv_prefix: "{{ amq_streams_operator_csv_prefix }}"

- name: "wait until amq streams operator deployment is created"
  kubernetes.core.k8s_info:
    kind: Deployment
    name: "not sure"
    namespace: "{{ namespace_amq_streams_operator }}"
    wait_sleep: 10
    wait_timeout: 90
