---

- name: Deploy djl-modelmanager
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - include: tasks/djl-modelmanager.yml
