---

- name: Deploy all quickstart resources
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
  vars:
    ACTION: install

  tasks:
  - include: tasks/djl-modelmanager.yml
  - include: tasks/djl-fprint.yml
