---

# The reason this file exists is because adding the following limit/request is not possible via kubernetes quarkus properties in src/main/resource/application.properties:
#   nvidia.com/gpu: "1"
 
# Related documentation: https://quarkus.io/guides/deploying-to-kubernetes#using-existing-resources


apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: djl-iclassification-tensorflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: djl-iclassification-tensorflow
    spec:
      containers:
        - name: djl-iclassification-tensorflow
          resources:
            limits:
              nvidia.com/gpu: '1'
            requests:
              nvidia.com/gpu: '1'
