---

- name: delete helm deployed resources
  kubernetes.core.helm:
    name: "{{ application_name }}"
    state: absent
    release_namespace: "{{ namespace }}"
    wait: true

- name: "delete configmap {{ application_configmap }}"
  k8s:
    state: absent
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    kind: ConfigMap

- name: "delete route {{ application_name }}"
  k8s:
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: Route
    api_version: route.openshift.io/v1
