---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ application_name }}
  labels:
    app: {{ application_name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ model_pv_capacity }}
