---

application_name: "{{ djl_fprint_app_name }}"

djl_engine: tensorflow
djl_processor: cpu
app_build_name: "{{ djl_fprint_app_name }}-{{ djl_engine }}-{{ djl_processor }}"

service_image: "quay.io/redhat_naps_da/{{ djl_fprint_app_name }}"
service_image_tag: 0.0.1

application_configmap: "{{ application_name }}"

helm_tar_url: "/u01/labs/mw/redhat-na-ssa/djl-intro/{{ application_name }}/target/helm/openshift/{{ app_build_name }}"
# helm_tar_url: "https://github.com/redhat-na-ssa/djl-intro/raw/main/{{ application_name }}/helm/{{ application_name }}-{{ service_image_tag }}.tar.gz"

model_pv_capacity: 5Gi
