---

- set_fact:
    namespace: "{{ namespace_ldap }}"
    resources_dir: "{{ resources_base_dir }}/ldap"
    work_dir_name: ldap
- include_role:
    name: ../roles/ldap
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"


- include_role:
    name: ../roles/ldap
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"
